# Generated by Django 6.0.3 on 2026-03-03 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('order', models.PositiveIntegerField()),
                ('lesson_type', models.CharField(choices=[('concept', 'Concept Lesson'), ('interactive', 'Interactive Example'), ('exercise', 'Exercise')], default='concept', max_length=20)),
                ('content', models.TextField(help_text='Markdown content for the lesson. Use code blocks for examples.')),
                ('sandbox_code', models.TextField(blank=True, default='', help_text='Pre-loaded code for the interactive sandbox.')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['module__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(unique=True)),
                ('icon', models.CharField(default='book', max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('order', models.PositiveIntegerField()),
                ('exercise_type', models.CharField(choices=[('fill_blank', 'Fill in the Blank'), ('fix_bug', 'Fix the Bug'), ('write_code', 'Write Code'), ('output_predict', 'Predict the Output')], default='write_code', max_length=20)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Starter'), (2, 'Easy'), (3, 'Medium'), (4, 'Challenging')], default=1)),
                ('instructions', models.TextField()),
                ('starter_code', models.TextField(blank=True, default='', help_text='Code pre-loaded in the editor. Use # TODO comments for guidance.')),
                ('solution_code', models.TextField(blank=True, default='', help_text='The reference solution for this exercise.')),
                ('choices', models.JSONField(blank=True, help_text='For output_predict: [{"label": "42", "is_correct": true}, ...]', null=True)),
                ('xp_value', models.PositiveIntegerField(default=10)),
                ('concepts', models.CharField(blank=True, default='', help_text="Comma-separated Python concepts (e.g., 'variables, print, strings')", max_length=300)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='curriculum.lesson')),
            ],
            options={
                'ordering': ['lesson__module__order', 'lesson__order', 'order'],
                'unique_together': {('lesson', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.module'),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(blank=True, default='', help_text='Input to pass to the code (simulated stdin or function args).')),
                ('expected_output', models.TextField(help_text='Expected output (stdout or return value).')),
                ('is_hidden', models.BooleanField(default=False, help_text="Hidden test cases aren't shown to the user before submission.")),
                ('description', models.CharField(blank=True, default='', help_text='Human-readable description of what this test checks.', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='curriculum.exercise')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(help_text='1=Nudge, 2=Concept, 3=Approach, 4=Walkthrough, 5=Solution')),
                ('content', models.TextField(help_text='Markdown hint content.')),
                ('xp_penalty_percent', models.PositiveSmallIntegerField(default=0, help_text='Percentage of XP deducted when this hint is revealed.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='curriculum.exercise')),
            ],
            options={
                'ordering': ['exercise', 'level'],
                'unique_together': {('exercise', 'level')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'slug')},
        ),
    ]
