# Generated by Django 6.0.3 on 2026-03-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='order',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
